module: TLDExtractSwift
version: 3.0.0

author: Kojiro Futamura
author_url: https://github.com/gumob
github_url: https://github.com/gumob/TLDExtractSwift
# copyright: 'Copyright © 2024 Kojiro Futamura. All rights reserved.'

source_host_url: https://github.com/gumob/TLDExtractSwift
root_url: https://github.com/gumob/TLDExtractSwift/tree/3.0.0/docs/

readme: "README.md"

theme: fullwidth

xcodebuild_arguments:
  - -project
  - ../TLDExtractSwift.xcodeproj
  - -scheme
  - TLDExtractSwift

output: "docs/swiftdoc"
min_acl: public
clean: true
skip_undocumented: false
hide_documentation_coverage: true
source_directory: Sources
umbrella_header: "Sources/TLDExtractSwift.h"

exclude:
  - Tests/*
